services:
  # 1. NestJS Backend Web Service
  - type: web
    name: edinz-quiz-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=450
      - key: DATABASE_URL
        value: postgresql://postgres.hrjusuvhekpnctcewmzs:Keeethee%402006@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=10&pool_timeout=15&sslmode=require
      - key: DIRECT_URL
        value: postgresql://postgres.hrjusuvhekpnctcewmzs:Keeethee%402006@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
      - key: JWT_SECRET
        value: SECRET_JWT_KEY_EDINZ

  # 2. Angular Frontend Static Site
  - type: web
    name: edinz-quiz-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
